# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_group_text', models.CharField(max_length=50)),
            ],
        ),
    ]
