# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_type',
            field=models.IntegerField(choices=[(-1, 'other'), (0, 'normal')], default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='options_type',
            field=models.IntegerField(choices=[(-1, 'radio'), (0, 'checkbox')], default=-1),
        ),
    ]
