# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_auto_20170506_0309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='numeric_value',
        ),
        migrations.RemoveField(
            model_name='question',
            name='options_type',
        ),
        migrations.AddField(
            model_name='answer',
            name='other_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='range_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='input_type',
            field=models.IntegerField(choices=[(-1, 'radio'), (0, 'checkbox'), (1, 'range'), (2, 'select'), (3, 'text')], default=-1),
        ),
        migrations.AddField(
            model_name='question',
            name='max_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='min_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='description',
            field=models.CharField(default='We have cancelled your account successfully. Please share your feedback with us.', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='survey',
            name='page_title',
            field=models.CharField(default='We will miss you!', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='survey.Choice'),
        ),
        migrations.AlterField(
            model_name='choicegroup',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
