# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20170506_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.ChoiceGroup'),
        ),
        migrations.AlterField(
            model_name='question',
            name='input_type',
            field=models.IntegerField(choices=[(-1, 'radio'), (0, 'checkbox'), (1, 'slider'), (2, 'dropdown'), (3, 'text')], default=-1),
        ),
    ]
