# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20170507_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
