# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20170510_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='username',
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='sub_date',
            field=models.DateTimeField(null=True, verbose_name='date submitted'),
        ),
    ]
