# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_submission_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='header_image',
            field=models.ImageField(null=True, upload_to='header_images/'),
        ),
    ]
